# Generated by Django 2.2.6 on 2020-03-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
