# Generated by Django 2.2.6 on 2019-11-02 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20191102_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
