# Generated by Django 2.2.6 on 2019-11-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20191102_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
