# Generated by Django 2.2.6 on 2019-11-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20191104_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
