# Generated by Django 2.2.6 on 2019-11-04 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20191104_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={},
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
