# Generated by Django 2.2.5 on 2019-11-16 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20191104_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricSystemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('script', models.FileField(upload_to='biometricSystem/')),
            ],
        ),
    ]
