# Generated by Django 2.2.5 on 2019-11-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_biometricsystemmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiometricSystemModel',
        ),
    ]
