# Generated by Django 2.2.6 on 2020-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subsystem', '0003_recordmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricsystemmodel',
            name='machineLModel',
            field=models.FileField(blank=True, null=True, upload_to='biometricSystem/models/'),
        ),
        migrations.AlterField(
            model_name='biometricsystemmodel',
            name='script',
            field=models.FileField(upload_to='biometricSystem/scripts/'),
        ),
    ]
