# Generated by Django 2.2.5 on 2020-01-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subsystem', '0005_auto_20200113_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricsystemmodel',
            name='portNum',
            field=models.IntegerField(null=True),
        ),
    ]
