# Generated by Django 2.2.5 on 2020-01-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subsystem', '0006_biometricsystemmodel_portnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricsystemmodel',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
