# Generated by Django 2.2.5 on 2020-01-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subsystem', '0007_biometricsystemmodel_isstarted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricsystemmodel',
            options={'verbose_name': 'Biometric System', 'verbose_name_plural': 'Biometric Systems'},
        ),
        migrations.AlterModelOptions(
            name='recordmodel',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AddField(
            model_name='recordmodel',
            name='processTime',
            field=models.FloatField(default=0),
        ),
    ]
