# Generated by Django 2.2.5 on 2020-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subsystem', '0008_auto_20200129_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmodel',
            name='isAccepted',
            field=models.BooleanField(default=True),
        ),
    ]
